### ISSUE TITLE
lib with another bluetooth module

### ISSUE THREAD

**Issue by maxholgasson** [aster94/GoProControl#16]
Hi, is there a way to use another bluetooth module instead of the ESP32 with your libary?

> BLE is not planned yet because in the ESP32 core is not so well supported or anyway bug-free

**Comment by aster94** [comment]
hi max,

honestly right now i don't plan to do this. The problem is not about the module but about which library to use. The reference for arduino, if i am not wrong, is set by [curieBLE](https://www.arduino.cc/en/Reference/CurieBLE) and i think (hope) that the ESP32 guys are following this to write their library.

However if you find any bluetooth library which is following 100% the arduino practise bringing inside this repo wouldn't be too hard and i may do it during the next months
